### ISSUE TITLE
Code Block

### ISSUE THREAD

**Issue by ngucthanh117** [nagaohiroki/AI_bot#1]
Can you add code block, please

**Comment by nagaohiroki** [comment]
'code block ' is 'discord code block '?

print('ok')
↓
\```python
print('ok')
\```

**Comment by nagaohiroki** [comment]
i have one idea. you can post to AI on discord. 
"@AI 
this place is Discord. If the text below contains program code, please write it in a Discord code block syntax."

**Comment by nagaohiroki** [comment]
closed. if you need then please comment. 
thanks!
